---
- name: check access
  hosts: all
  become: true
  tasks:
    - name: full access to my hosts correctly
      become: true
      command: whoami
      register: whoami_output

    - name: print whoami output
      debug:
        var: whoami_output.stdout